### ISSUE TITLE
chore:  bump version and tag repo with 0.9.2 so bower can install by version.

### ISSUE THREAD

**Issue by macneib** [axilleasiv/angular-quill#1]
Hey, nice little project here.
I'd like to bower install by version. it's a simple fix. like so:

```
vim bower.json
#change
"version": "0.9.2",

# commit your changes
git commit -am "added 0.9.2 tag to repo"

# tag the commit
git tag -a v0.9.1 -m "Release version 0.9.2"

# push to GitHub
git push origin master --tags  
```

**Comment by axilleasiv** [comment]
@macneib you have right about this :+1: I did what you said except the first step -- no vim bower.json, just subl bower.json :). If you have any problem again with the bower, or with the angular directive, tell me, thanks a lot
